name: build and run
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cd ..
      - run: sudo apt-get update && sudo apt-get install -y cmake
      - run: cmake -B build
      - run: cmake --build build
      - run: ./build/main 3 6
